services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: elbrezal-sqlserver
    restart: unless-stopped

    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "${MSSQL_SA_PASSWORD}"
      MSSQL_PID: "Developer"

    ports:
      - "1433:1433"

    volumes:
      - elbrezal-sqlserver-data:/var/opt/mssql

volumes:
  elbrezal-sqlserver-data: